from dataclasses import dataclass
from datetime import datetime
from typing import Any
from typing import Protocol
from uuid import UUID

from app.schemas.common import ConsentState, DeviceClass, RenderMode
from app.schemas.world import WorldStateSchema


@dataclass(slots=True)
class SessionRecord:
    session_id: UUID
    seed: str
    locale: str
    device_class: DeviceClass
    render_mode: RenderMode
    timezone_offset_minutes: int
    prefers_reduced_motion: bool
    consent: ConsentState
    created_at: datetime
    updated_at: datetime
    expires_at: datetime


class SessionRepositoryProtocol(Protocol):
    async def create(self, record: SessionRecord) -> SessionRecord: ...
    async def get(self, session_id: UUID) -> SessionRecord | None: ...
    async def update(self, record: SessionRecord) -> SessionRecord: ...
    async def delete(self, session_id: UUID) -> None: ...
    async def count_active(self, now: datetime) -> int: ...
    async def ping(self) -> bool: ...


class WorldSnapshotRepositoryProtocol(Protocol):
    async def save_snapshot(self, session_id: UUID, state: WorldStateSchema) -> WorldStateSchema: ...
    async def get_latest(self, session_id: UUID) -> WorldStateSchema | None: ...
    async def delete_for_session(self, session_id: UUID) -> None: ...


class PresenceRepositoryProtocol(Protocol):
    async def heartbeat(self, session_id: UUID) -> None: ...
    async def join_room(self, room_id: str, session_id: UUID, payload: dict[str, Any]) -> None: ...
    async def update_presence(self, room_id: str, session_id: UUID, payload: dict[str, Any]) -> None: ...
    async def list_room(self, room_id: str) -> list[dict[str, Any]]: ...
    async def remove_session(self, room_id: str, session_id: UUID) -> None: ...
    async def clear_session(self, session_id: UUID) -> None: ...
    async def ping(self) -> bool: ...
